//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrnspMngmntDataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTransportManagementEntities : DbContext
    {
        public DBTransportManagementEntities()
            : base("name=DBTransportManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOS { get; set; }
        public virtual DbSet<CITy> CITIES { get; set; }
        public virtual DbSet<DEPARTURE> DEPARTURES { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRAILER> TRAILERs { get; set; }
        public virtual DbSet<TRAILER_TYPES> TRAILER_TYPES { get; set; }
        public virtual DbSet<TRUCK> TRUCKs { get; set; }
        public virtual DbSet<TRUCK_TYPES> TRUCK_TYPES { get; set; }
        public virtual DbSet<TRUCKER> TRUCKERS { get; set; }
    }
}
