//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrnspMngmntDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAILER()
        {
            this.TRUCKs = new HashSet<TRUCK>();
        }
    
        public int TRAILER_ID { get; set; }
        public Nullable<System.DateTime> TRAILER_LAST_OVERHAUL { get; set; }
        public Nullable<int> TRAILER_SERIAL_NUMBER { get; set; }
        public Nullable<int> TRAILER_TYPE { get; set; }
    
        public virtual TRAILER_TYPES TRAILER_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUCK> TRUCKs { get; set; }
    }
}
