//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrnspMngmntDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAILER_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAILER_TYPES()
        {
            this.TRAILERs = new HashSet<TRAILER>();
        }
    
        public int TYPE_TR_ID { get; set; }
        public string TYPE_TR_MODEL { get; set; }
        public Nullable<int> TYPE_TR_CAPACITY { get; set; }
        public string TYPE_TR_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAILER> TRAILERs { get; set; }
    }
}
