//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrnspMngmntDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUCKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRUCKER()
        {
            this.CARGOS = new HashSet<CARGO>();
        }
    
        public int TR_ID { get; set; }
        public string TR_NAME { get; set; }
        public string TR_SURNAME { get; set; }
        public Nullable<System.DateTime> TR_BIRTH { get; set; }
        public Nullable<System.DateTime> TR_START_DRIVE { get; set; }
        public Nullable<int> TR_TRUCK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGO> CARGOS { get; set; }
        public virtual TRUCK TRUCK { get; set; }
    }
}
